version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:2022.05
    steps:
      - setup_remote_docker:
          version: default
      - checkout
      - run:
          name: Authenticate to Docker Hub
          command: echo $DOCKER_TOKEN | docker login -uticketingevents --password-stdin
      - run: 
          name: Build Moko Gateway base image
          command: docker build -t ticketingevents/moko-gateway:$CIRCLE_TAG -t ticketingevents/moko-gateway:latest .
      - run:
          name: Publish Mogo Gateway base image to Docker Hub
          command: |
            docker push ticketingevents/moko-gateway:$CIRCLE_TAG
            docker push ticketingevents/moko-gateway:latest

workflows:
  publish_to_docker:
    jobs:
      - build_and_push:
          context:
            - Build Secrets 
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
